"""add user phone number + otp request

Revision ID: 3309ca2dfdd5
Revises: 0bf245aaffe3
Create Date: 2024-07-13 15:37:29.085621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import core


# revision identifiers, used by Alembic.
revision: str = '3309ca2dfdd5'
down_revision: Union[str, None] = '0bf245aaffe3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp_requests',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('status', core.db.models.Enum('pending', 'expired', name='status', native_enum=False), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('user_id', 'otp_requests', ['status'], unique=True, postgresql_where=sa.text("status = 'pending'"))
    op.add_column('users', sa.Column('phone_number', sa.Text(), nullable=False))
    op.add_column('users', sa.Column('status', core.db.models.Enum('new', 'pending', 'complete', name='status', native_enum=False), nullable=False))
    op.create_unique_constraint(None, 'users', ['phone_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'status')
    op.drop_column('users', 'phone_number')
    op.drop_index('user_id', table_name='otp_requests', postgresql_where=sa.text("status = 'pending'"))
    op.drop_table('otp_requests')
    # ### end Alembic commands ###
