services:
  # web:
  #   build: .
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - APP_MODULE=main.app:app
  #     - PORT=8000
  postgres:
    image: postgres:14
    container_name: postgres14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
